version: "3.8"

services:
  db:
    image: mysql:8.1
    container_name: adonis_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: adonis_db
      MYSQL_USER: adonis_user
      MYSQL_PASSWORD: adonis_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - adonis_network

volumes:
  db_data:

networks:
  adonis_network:
    driver: bridge