/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  users: {#controllers/purchase/purchase_controller
    AccessToken: () => import('#controllers/users/access_token_controller'),
    NewAccount: () => import('#controllers/users/new_account_controller'),
    Product: () => import('#controllers/users/product_controller'),
    Profile: () => import('#controllers/users/profile_controller'),
  },
  purchase: {
    Purchase: () => import('#controllers/purchase/purchase_controller'),
  },
}
