/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Client: () => import('#controllers/client_controller'),
  Gateway: () => import('#controllers/gateway_controller'),
  Product: () => import('#controllers/product_controller'),
  Purchase: () => import('#controllers/purchase_controller'),
  User: () => import('#controllers/user_controller'),
}
